config = {
    'exp_name' : 'document',
    'epoch' : 100,
    'lr' : 1,
    'batch' : 128,
    'val_frequency' : 100,
    'test' : False,
    'resume_model' : './final_model.pth',
    'train_dataset' : '',
    'validation_dataset': '',
    'inference_dataset': './datas',
    'judge_dataset': '',
    'schedule_frequency' : 10,
    'imageH' : 32,
    'imageW' : 256,
    'encoder' : 'resnet',
    'decoder' : 'transformer',
    'alpha_path' : './data/char_handwriting_Chinese.txt',
    'radical_path': './data/radical_all_Chinese_2.txt',
    'decompose_path': './data/decompose.txt',
    'pre-train_model': './adult_pre_train_model.pth',
    'stn': False,
    'constrain': False,
    'char_len' : 60,
}
